spring:
  datasource:
    password: ivoyant@123
    url: jdbc:mysql://mysqlgit.mysql.database.azure.com:3306/movie1
    username: adarsh


#JPA Settings

  jpa:
    hibernate:
      ddl-auto=update:
